PR for Issue #170
pypa/trove-classifiers pull request #171
Opened 2024-01-31 23:17 UTC by tcaduser

Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `License :: OSI Approved :: Educational Community License v2.0 (ECL-2.0)`

## Why do you want to add this classifier?

This OSI approved license is part of my project, and is missing from the approved classifiers.

2024-02-22 17:29 UTC, di requested changes

2024-02-22 17:29 UTC, di commented on src/trove_classifiers/__init__.py
> +    "License :: OSI Approved :: Educational Community License v2.0 (ECL-2.0)",
```suggestion
    "License :: OSI Approved :: Educational Community License, Version 2.0 (ECL-2.0)",
```
A small nit, but we should try to keep this as close as possible to the OSI name for the license.

2024-02-22 19:29 UTC, tcaduser commented
thanks

2024-02-23 16:42 UTC, di approved these changes

2024-02-23 16:43 UTC, merged